---
- name: Deploy Fitness Booking System
  hosts: fitness_app
  become: true
  tasks:

    - name: Install Docker and docker-compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Log into Docker Hub (optional if private images)
      docker_login:
        username: "{{ docker_hub_user }}"
        password: "{{ docker_hub_pass }}"
      when: docker_hub_user is defined and docker_hub_pass is defined

    - name: Pull latest Docker images
      shell: docker-compose pull
      args:
        chdir: /home/pelin/fitness-app

    - name: Run docker-compose up -d
      shell: docker-compose up -d
      args:
        chdir: /home/pelin/fitness-app
