# Generated by Django 5.1.7 on 2025-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images/'),
        ),
    ]
