name: Code Testing and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
            python-version: "3.10"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
            pip install pre-commit black
            pre-commit install

   
